name: capybara-hub

services:
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=capybara_hub

volumes:
  mongodb_data:
